name: CI
on: 
  pull_request:
    branches: ["staging", "main"]
  push:
    branches: ["staging", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: myKey-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            myKey-
      - name: use node
        uses: actions/setup-node@v1
        with: 
          node-version: "14.x"
      - run: npm ci
      - run: npm test -- --coverage
        env: 
          CI: true
      - name: upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      - name: build app
        run: npm run build
      - name: upload build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: deploy app
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain strange-limit.surge.sh
        env:
          SURGE_USER: ${{ secrets.SURGE_USER }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}




