name: CI
on: 
  pull_request:
    branches: ["staging"]
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with: 
          node_version: "14.18.0"
      - run: npm ci
      - run: npm test -- --coverage
        env: 
          CI: true
      - name: build app
        run: npm run build
      - name: deploy app
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain strange-limit.surge.sh
        env:
          SURGE_USER: ${{ secrets.SURGE_USER }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}




