name: Matrix Commands

on: [pull_request]

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [14,16,18]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Log node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Log node version
        run: node -v
